name: PR Checks

on:
  pull_request:
    branches:
      - main  # Run this action for pull requests targeting the 'main' branch

jobs:
  run-checks:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          ./gradlew test  # Run unit tests (using Gradle)
