name: PR Checks

on:
  pull_request:
    branches:
      - main  # Run this action for pull requests targeting the 'main' branch

jobs:
  run-checks:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up a job to run tests or checks
      - name: Run unit tests
        run: |
          pytest  # Replace with the command for running tests in your project


