name: PR Checks

on:
  pull_request:
    branches:
      - main  # Run this action for pull requests targeting the 'main' branch

jobs:
  run-checks:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install dependencies
        run: |
          ./gradlew build --no-daemon  # Run Gradle build (assuming you're using Gradle)

      - name: Run tests
        run: |
          ./gradlew test  # Run unit tests (using Gradle)
